### ISSUE TITLE
请问是在Ubuntu下编译的吗，我用mac系统编译到最后会出问题，有用ci吗

### ISSUE THREAD

**Issue by foezzy** [2dust/AndroidLibV2rayLite#22]

**Comment by 2dust** [comment]
ci是可以的
buuntu也是可以的
都需要自己折腾下

**Comment by foezzy** [comment]
(/Users/kree/go/src/google.golang.org/grpc/internal/transport/http2_client.go:1149:51: MetaHeadersFrame not declared by package http2)  编译碰到这个错，请问这是什么原因呢

**Comment by 2dust** [comment]
此项目合并至 https://github.com/2dust/v2rayNG/tree/master/AndroidLibV2rayLite
编译请自己google，网上有很多教程的
