### ISSUE TITLE
(/Users/kree/go/src/google.golang.org/grpc/internal/transport/http2_client.go:1149:51: MetaHeadersFrame not declared by package http2)  编译碰到这个错，请问这是什么原因呢

### ISSUE THREAD

**Issue by foezzy** [2dust/AndroidLibV2rayLite#23]
(/Users/kree/go/src/google.golang.org/grpc/internal/transport/http2_client.go:1149:51: MetaHeadersFrame not declared by package http2)  编译碰到这个错，请问这是什么原因呢

_Originally posted by @foezzy in https://github.com/2dust/AndroidLibV2rayLite/issues/22#issuecomment-521304323_

原来是需要下载很多依赖包，然后包又要用最新的，报了很多都是这样的错~有办法一次自动拉下来吗

**Comment by 2dust** [comment]
此项目合并至 https://github.com/2dust/v2rayNG/tree/master/AndroidLibV2rayLite
编译请自己google，网上有很多教程的
