### ISSUE TITLE
请问tun2socks是怎么编译进去的？

### ISSUE THREAD

**Issue by tcwdsg** [2dust/AndroidLibV2rayLite#24]
看到了有启动tun2socks的代码，也看到了尝试用go-bindata来打包
也看到了complie-tun2socks.sh  的脚本
但是脚本编译后的东西似乎没有打包入aar
实际执行的时候也的确在/data/data下没有找到tun2socks

**Comment by 2dust** [comment]
此项目合并至 https://github.com/2dust/v2rayNG/tree/master/AndroidLibV2rayLite
编译请自己google，网上有很多教程的
